models/Complaint.php
<?php

namespace app\models;

use Yii;
use app\models\Customer;

/**
 * This is the model class for table "tbl_order".
 *
 * @property integer $order_id
 * @property integer $merchant_id
 * @property integer $client_id
 * @property string $json_details
 * @property string $trans_type
 * @property string $payment_type
 * @property double $sub_total
 * @property double $tax
 * @property string $taxable_total
 * @property double $total_w_tax
 * @property string $status
 * @property integer $stats_id
 * @property string $contact_phone
 * @property string $email_address
 * @property string $door
 * @property string $street
 * @property string $city
 * @property integer $zipcode
 * @property integer $viewed
 * @property double $delivery_charge
 * @property string $delivery_date
 * @property string $delivery_time
 * @property string $delivery_asap
 * @property string $delivery_instruction
 * @property string $voucher_code
 * @property double $voucher_amount
 * @property string $voucher_type
 * @property integer $cc_id
 * @property string $date_created
 * @property string $date_modified
 * @property string $ip_address
 * @property double $order_change
 * @property string $payment_provider_name
 * @property double $discounted_amount
 * @property double $discount_percentage
 */
class Complaint extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_complaint';
    }
	
	 public function getjob()
	{
		//return $this->hasOne(Client::className(), ['to_id' => $user_id,'status' => 'pending'])->from(['tbl_job_assign' => Client::tableName()]);
		//return $this->hasOne(Job::className(), ['status' => 'pending'])->from(['tbl_job_assign' => Job::tableName()]);
		 return $this->hasOne(Job::className(), ['complaint_id' => 'complaint_id']);
		//return $this->hasOne(Client::className(), ['client_id' => 'client_id']);
	}
	
	public function getcustomerdetails()
	{
		//return $this->hasOne(Client::className(), ['to_id' => $user_id,'status' => 'pending'])->from(['tbl_job_assign' => Client::tableName()]);
		//return $this->hasOne(Job::className(), ['status' => 'pending'])->from(['tbl_job_assign' => Job::tableName()]);
		 return $this->hasOne(Customer::className(), ['id' => 'customer_id']);
		//return $this->hasOne(Client::className(), ['client_id' => 'client_id']);
	}

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['first_name', 'last_name', 'email_address', 'contact_phone', 'Address', 'date_created', 'status'], 'required'],
            /*[['merchant_id', 'client_id', 'stats_id', 'zipcode', 'viewed', 'cc_id'], 'integer'],
            [['json_details', 'street'], 'string'],
            [['sub_total', 'tax', 'taxable_total', 'total_w_tax', 'delivery_charge', 'voucher_amount', 'order_change', 'discounted_amount', 'discount_percentage'], 'number'],
            [['delivery_date', 'date_created', 'date_modified'], 'safe'],
            [['trans_type', 'payment_type', 'delivery_time', 'voucher_code', 'voucher_type'], 'string', 'max' => 100],
            [['status', 'delivery_instruction', 'payment_provider_name'], 'string', 'max' => 255],
            [['contact_phone'], 'string', 'max' => 20],
            [['email_address', 'ip_address'], 'string', 'max' => 50],
            [['door', 'city'], 'string', 'max' => 30],
            [['delivery_asap'], 'string', 'max' => 14],*/
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'first_name' => 'Customer first name',
            'last_name' => 'Last_name',
            'email_address' => 'Email Adress',
            'contact_phone' => 'Mobile',
            'Address' => 'Address',
            'date_created' => 'Date',
			'status' => 'Status',
            
        ];
    }
}

controllers/ComplaintController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\Sales_search;
use app\models\Complaint;
use app\models\Complaintsearch;
use app\models\Complaintmerge;
use app\models\Job;
use app\models\Customer;
use app\models\Customersearch;
use app\models\Customvalidation;
use app\models\Vendor;
use app\models\Vendorsearch;
use app\models\Purchase;
use app\models\Products;
use app\models\Stocksearch;
use app\models\Sales;
use app\models\Group_sales;
use app\models\Shop;

use kartik\mpdf\Pdf;
use yii\helpers\ArrayHelper;
use app\models\Inventory;

class ComplaintController extends Controller
{
    /**
     * @inheritdoc
     */
	// public $layout=false;
    public function behaviors()
    {
       return [
        'ghost-access'=> [
            'class' => 'webvimark\modules\UserManagement\components\GhostAccessControl',
        ],
    ];
    }

    
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
	 
	 
	 public function actionReport() {
		 $this->layout = false;
		// get your HTML raw content without any layouts or scripts
	    $htmlContent = $this->renderPartial('reportView', ['model'=>$_GET['id']]);
				// $htmlContent = 'kumar';
			$pdf = Yii::$app->pdf;
		$pdf->content = $htmlContent;
		return $pdf->render();
       }
	   
    public function actionGet_team_member() 
	{
		$team_users='';
		$team_name=$_GET['team_name'];
		$Results = Yii::$app->db->createCommand("SELECT user_id FROM auth_assignment Where item_name='$team_name'")->queryAll(); 
		foreach($Results as $user)
		{
		  $result=Yii::$app->mycomponent->Get_user($user['user_id']);
		  $team_users[$user['user_id']]=$result['firstname'];
		}
		               $response =  ['status' => 1,
								    'team_users' => $team_users,];
		return json_encode($response);
    }
	   
	    public function actionBill() {
		 $this->layout = false;
		// get your HTML raw content without any layouts or scripts
	    $htmlContent = $this->renderPartial('billView');
				// $htmlContent = 'kumar';
			$pdf = Yii::$app->pdf;
		$pdf->content = $htmlContent;
		return $pdf->render();
       }		   
	 
    public function actionIndex()
    {
       	$searchModel = new Complaintsearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize=10;
		$dataProvider->setSort([
        'defaultOrder' => ['priority'=>SORT_DESC],]);
        return $this->render('complaint', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
	
	public function actionEstimate()
    {
		$searchModel = new Sales_search();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,'service_sno');
        $dataProvider->pagination->pageSize=10;
		$dataProvider->setSort([
        'defaultOrder' => ['id'=>SORT_DESC],]);
        return $this->render('sales', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
      
    }
	
	public function actionRegister()
    {
		$searchModel = new Customvalidation();
       return $this->render('register',['model'=>$searchModel]);
    }
	public function actionView_complaint()
    {
		//$searchModel = new Customvalidation();
       return $this->render('view_complaint');
    }
	public function actionJobassign()
    {
		$type=$_GET['type'];
		$complaint_id=$_GET['complaint_id'];
		//Yii::$app->mycomponent->Complaint_create();
       return $_GET['type'];
    }
	public function actionCreate()
    {
		 $redirect=Yii::$app->request->post('render');
        $complaint_id=Yii::$app->mycomponent->Complaint_create();
		if($complaint_id!='')
		{
	      return $this->redirect([$redirect,'id'=>$complaint_id]);
		}
		else
		{
			return $this->redirect([$redirect]);
		}
		
    }
	
	public function actionMob_validation()
    {
		
        $result=Yii::$app->mycomponent->Mob_validation($_GET['mob']);
		if($result)
						{
						$response = ['status' => 1,
								'results' => $result,
								];
						}
						else
						{
							$response = ['status' => 2,
								'results' =>'No results found',
								];
						}
	    return json_encode($response);
    }

	public function actionComplaint()
    {
		$searchModel = new Complaintsearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize=10;
		$dataProvider->setSort([
        'defaultOrder' => ['priority'=>SORT_DESC],]);
        return $this->render('complaint', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
      
    }
	public function actionNewcustomer()
    {
        $model = new Customer();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            // valid data received in $model
			$model->first_name = $_POST['Customer']['first_name'];
            $model->last_name = $_POST['Customer']['last_name'];
            $model->Address = $_POST['Customer']['Address'];
            $model->city = $_POST['Customer']['city'];
			$model->contact_phone = $_POST['Customer']['contact_phone'];
			$model->email_address = $_POST['Customer']['email_address'];
			$model->company_name = $_POST['Customer']['company_name'];
			$model->tin_no = $_POST['Customer']['tin_no'];
			$model->office_no = $_POST['Customer']['office_no'];
			$model->date_created = date('Y-m-d H:i:s');
			$model->pincode = $_POST['Customer']['pincode'];
			$model->state = $_POST['Customer']['state'];
			$model->cst_number = $_POST['Customer']['cst_number'];
			$model->opening_balance = $_POST['Customer']['opening_balance'];
            $model->selling_id = $_POST['selling_id'];
			$model->notes = $_POST['Customer']['notes'];
            // do something meaningful here about $model ...
			if ($model->save())
			{
				//Yii::$app->response->redirect(array('complaint/customers'));
				return Yii::$app->response->redirect(array('complaint/customers'));
			}

            
        } else {
            // either the page is initially displayed or there is some validation error
            //return $this->render('customer', ['model' => $model]);
			return $this->render('new', ['model' => $model]);
        }
    }
	
	public function actionNewvendor()
    {
        $model = new Vendor();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            // valid data received in $model
			$model->first_name = $_POST['Vendor']['first_name'];
           // $model->last_name = $_POST['Vendor']['last_name'];
            $model->Address = $_POST['Vendor']['Address'];
            $model->city = $_POST['Vendor']['city'];
			$model->contact_phone = $_POST['Vendor']['contact_phone'];
			$model->email_address = $_POST['Vendor']['email_address'];
			$model->company_name = $_POST['Vendor']['company_name'];
			$model->tin_no = $_POST['Vendor']['tin_no'];
			$model->office_no = $_POST['Vendor']['office_no'];
			$model->state = $_POST['Vendor']['state'];
			$model->pincode = $_POST['Vendor']['pincode'];
			$model->cst_number = $_POST['Vendor']['cst_number'];
			$model->opening_balance = $_POST['Vendor']['opening_balance'];
			$model->office_no = $_POST['Vendor']['pincode'];
			$model->notes = $_POST['Vendor']['notes'];
			if ($model->save())
			{
				//Yii::$app->response->redirect(array('complaint/customers'));
				return Yii::$app->response->redirect(array('complaint/vendor'));
			}

            
        } else {
            // either the page is initially displayed or there is some validation error
            //return $this->render('customer', ['model' => $model]);
			//var_dump($model->errors);
			//print_r($model->getErrors());
			return $this->render('new_vendor', ['model' => $model]);
        }
    }
	
	public function actionDeletecustomer()
    {
		$customer_id = $_GET['id'];
        $model = Customer::findOne(['id' =>$customer_id ]);
    	$model->delete();
       return Yii::$app->response->redirect(array('complaint/customers'));
    }
	
	public function actionDeletevendor()
    {
		$customer_id = $_GET['id'];
        $model = Vendor::findOne(['id' =>$customer_id ]);
    	$model->delete();
       return Yii::$app->response->redirect(array('complaint/vendor'));
    }
	public function actionDelete()
    {
		$complaint_id = $_GET['id'];
        $model = Complaint::findOne(['complaint_id' =>$complaint_id ]);
    	$model->delete();
       return Yii::$app->response->redirect(array('complaint/complaint'));
    }
	
	
	
	public function actionUpdatecustomer()
    {
        $customer_id = $_GET['id'];
		$model = Customer::findOne(['id' =>$customer_id ]);
          //$model = User::find()->where(['id' => $id])->one();
        if ($model->load(Yii::$app->request->post())&& $model->validate()) {
            // valid data received in $model
			$model->first_name = $_POST['Customer']['first_name'];
            $model->last_name = $_POST['Customer']['last_name'];
            $model->Address = $_POST['Customer']['Address'];
            $model->city = $_POST['Customer']['city'];
			$model->contact_phone = $_POST['Customer']['contact_phone'];
			$model->email_address = $_POST['Customer']['email_address'];
			$model->date_created = date('Y-m-d H:i:s');
			$model->company_name = $_POST['Customer']['company_name'];
			$model->tin_no = $_POST['Customer']['tin_no'];
			$model->office_no = $_POST['Customer']['office_no'];
			
			$model->pincode = $_POST['Customer']['pincode'];
			$model->state = $_POST['Customer']['state'];
			$model->cst_number = $_POST['Customer']['cst_number'];

views/complaint/customer.php
<?php 
use yii\helpers\Html;
use yii\widgets\ActiveForm;

 use yii\helpers\BaseHtml;
 use yii\helpers\Url;
 use yii\helpers\ArrayHelper;
 use kartik\grid\GridView;
 use yii\data\ActiveDataProvider;
 use \app\models\Articles;
 //use app\models\Orders;
 use yii\data\SqlDataProvider;


$this->title = 'Customers | '.Yii::$app->mycomponent->Get_settings('company_name'); 
/*$merchant_id= Yii::$app->user->identity->merchant_id;
$users=Yii::$app->mycomponent->All_users();
$Orders=Yii::$app->mycomponent->Orders($merchant_id);*/

$bgStatus='';

echo GridView::widget([
    'dataProvider'=>$dataProvider,
    'filterModel'=>$searchModel,
    'showPageSummary'=>true,
    'pjax'=>true,
    'striped'=>true,
    'hover'=>true,
	'headerRowOptions'=>['class'=>'kartik-sheet-style'],
    'filterRowOptions'=>['class'=>'kartik-sheet-style'],
	    'toolbar'=> [
        ['content'=>
            Html::a('<i class="glyphicon glyphicon-plus"></i>', ['newcustomer'],['data-pjax'=>0,  'title'=> 'Add', 'class'=>'btn btn-success', ]) . ' '.
            Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['index'], ['data-pjax'=>0, 'class'=>'btn btn-default', 'title'=> 'Reset Grid'])
        ],
        //'{export}',
        '{toggleData}',
    ],
    'panel'=>['type'=>'primary', 'heading'=>'Customers'],
    'columns' => [
       
		  [
		    'label'=>'Name',
		    'attribute'=>'company_name',
			'value'=>'company_name',
          ],
       
		  [
		    'label'=>'Contact Person',
		    'attribute'=>'first_name',
			'value'=>'first_name',
          ],
		   [
            'attribute'=>'contact_phone',
		  ],
		  
		  [
            'attribute'=>'Address',
           
          ],
		  
		  [
            'attribute'=>'city',
           
          ],
		  
		 
		  
		  [
		     'label'=>'Email',
            'attribute'=>'email_address',
			//'contentOptions' => ['class' => 'text-center'],
			// 'headerOptions' => ['class' => 'text-center']
          ],
		
		
		
		
		
		
		
		[
            'attribute'=>'date_created',
            //'pageSummary'=>'Page Summary',
           // 'pageSummaryOptions'=>['class'=>'text-right text-warning'],
        ],
		
		
	
		
		['class' => 'kartik\grid\ActionColumn',
              'header' => 'Actions',
              'template' => '{edit} {delete}',
              'buttons' => [
                
                 'edit' => function ($url, $model) {
                   return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url);
                 },
                 'delete' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url,[
                    'title' => Yii::t('yii', 'Delete'),
                    'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this Customer?'),
                    'data-method' => 'post',
                ]);
                 },
              ],
              'urlCreator' => function ($action, $model, $key, $index) {

                if ($action === 'assign') {
                    $url ='' ;
                }
                if ($action === 'edit') {
                    $url = Url::to(['/complaint/updatecustomer', 'id' =>$model->id]);
                }
                if ($action === 'delete') {
                    $url = Url::to(['/complaint/deletecustomer', 'id' =>$model->id]);
                }                    
                return $url;
            }
          ],
		
    ],
]);
$Rolls=Yii::$app->mycomponent->GetRolls();

?>
 
 

<div id="state-list"></div>

<div id="receipt"></div>
<input type="hidden" data-toggle="modal" data-target="#show_receipt" class="receipt_trigg"/>

<input type="hidden" data-toggle="modal" data-target="#assign_to" class="assign_to"/>
	<script>
    function assign_complaint(complaint_id) 
    {
    
       // alert(complaint_id);
		$("#cid").val(complaint_id);
		$(".assign_to").trigger('click');
        
    }
    </script>


<script>
function status_change(order_id) {
//alert(order_id);
//var x=val.split(',');
//alert(x[1]);
	$.ajax({
	type: "POST",
	url: '<?php echo Yii::$app->request->baseUrl. '/admin/status_change' ?>',
	data:'order_id='+order_id,
	success: function(data){
	//alert(data);
		$("#state-list").html(data);
		$("#stc").trigger('click');
	}
	});
}
</script>


<script>
function edit_complaint(order_id) {

//alert(order_id);
	$.ajax({
	type: "GET",
	url: '<?php echo Yii::$app->request->baseUrl. '/complaint/register' ?>',
	data:'order_id='+order_id,
	success: function(data){
	alert(data);
		$("#receipt").html(data);
		$(".receipt_trigg").trigger('click');
	}
	});
}
</script>

<script>
function st_change(val) {

var status=$('#st').val();
//alert(status);
	$.ajax({
	type: "POST",
	url: '<?php echo Yii::$app->request->baseUrl. '/admin/status_update' ?>',
	data:'id='+status+'&order_id='+val,
	success: function(data){
	//alert("#status_"+val);
	
		$("#status_"+val).html(data);
		$("#cls").trigger('click');
	}
	});
}


</script>


<div class="modal fade" id="assign_to" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div id="tableContainer-1">
    <div id="tableContainer-2">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
		    
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <i class="fa fa-times"></i>
            </button>
          </div>          
          <div id="div-forms" class="dropmenu-div" style="padding:10px;">
            <form class="form form-horizontal" name="" method="post"  >            
                
                 <input type="hidden" id='cid' name="cid"  />
                            
               <div class="form-group row">
               <label class="control-label col-sm-4"  value="Schema Name">Assign to </label>
               <div class="col-sm-8"> 
			   <select name="role" id="role" class="form-control" id="week-list">
               <?php foreach($Rolls as $rolle) { ?>
                  <option value="<?php echo $rolle['item_name'] ?>"><?php echo ucfirst($rolle['item_name']) ?></option>
                  
                  <?php } ?>
               </select>
			   </div> 
               </div>
               
               <div class="form-group row">
               <label class="control-label col-sm-4"  value="Schema Name">Notes</label>
               <div class="col-sm-8"> 
			  <textarea name="notes" id="notes" style="width: 100%;min-height: 100px;"></textarea>
			   </div> 
               </div>
              
            <div class="form-group row">
              <div class="text-center">
               
           <input class="btn btn-success" type="button" onclick="st_assign()" name="smt"  value="Assign" />
           <input class="btn btn-danger" type="submit"  data-dismiss="modal" value="Cancel" aria-label="Close"/>
            
           </div>
           </div>
            </form>        
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
function st_assign()
 {

var cid=$('#cid').val();
var notes=$('#notes').val();
var role=$('#role').val();
//alert(status);
	$.ajax({
	type: "POST",
	url: '<?php echo Yii::$app->request->baseUrl. '/admin/roleassign' ?>',
	data:'cid='+cid+'&notes='+notes+'&role='+role,
	success: function(data){
	//alert(data);
	
		//$("#status_"+val).html(data);
		$(".close").trigger('click');
	}
	});
}


</script>
        



<!-- View receipt button -->



<!--<a class="btn btn-info btn-lg" data-toggle="modal" data-target="#show_receipt">View Receipt</a>-->

views/complaint/job_assign.php
<?php
//print_r($model->products);
 $complaint_id=$model->complaint_id;

?>

<div class="col-sm-4">
            <table class="table table-bordered table-condensed table-hover small kv-table">
                <tbody><tr class="danger">
                    <th colspan="3" class="text-center text-success">Assign Job</th>
                </tr>
                <tr class="active">
                    <th class="text-center">1</th>
                    <th>Checking Dept</th>
                    <th class="text-right"><a onclick="assign_job('checking')" >Assign</a></th>
                </tr>
                <tr class="active">
                    <th class="text-center">2</th>
                    <th>Chiplevel Dept</th>
                    <th class="text-right"><a onclick="assign_job('chip')" >Assign</a></th>
                </tr>
                
                
            </tbody></table>
        </div>
        
        <script>
			function assign_job(type) {
			var complaint="<?php echo $complaint_id;?>";
			alert(type);
				$.ajax({
				type: "GET",
				url: '<?php echo Yii::$app->request->baseUrl. '/complaint/jobassign' ?>',
				data:'type='+type+'&complaint_id='+complaint,
				success: function(data){
				alert(data);
					
				}
				});
			}
     </script>
       
		 
         

views/complaint/purchase_list.php
<?php
//print_r($model->products);
$products=$model;
//echo 'Hi';
$i=1;
 use app\models\Products;
?>
<?php foreach($products as $val): ?>
<div class="col-sm-4">
            <table class="table table-bordered table-condensed table-hover small kv-table">
                <tbody><tr class="danger">
                    <th colspan="3" class="text-center text-danger">Product <?php echo $i; ?></th>
                </tr>
                <!--<tr class="active">
                    <th class="text-center">#</th>
                    <th>Breakup</th>
                    <th class="text-right">Price</th>
                </tr>-->
                <tr>
                    <td class="text-center">1</td><td><?php echo 'Product_id'; ?></td><td class="text-right"><?php echo $val['product_id']; ?> </td>
                </tr> 
                <tr>
                    <td class="text-center">1</td><td><?php echo 'Product_Name'; ?></td><td class="text-right"><?php  if($val['product_id']) { $model1 = Products::findOne(['pid'=>$val['product_id']]); echo $model1->product_name; } ?> </td>
                </tr>
                <tr>
                    <td class="text-center">2</td><td><?php echo 'Quantity'; ?></td><td class="text-right"><?php echo abs($val['qty']); ?> </td>
                </tr>
                <tr>
                    <td class="text-center">3</td><td><?php echo 'Price'; ?></td><td class="text-right"><?php echo $val['price']; ?> </td>
                </tr>
                <?php /*?><tr>
                    <td class="text-center">3</td><td><?php echo 'Shop'; ?></td><td class="text-right"><?php echo $val['shop']; ?> </td>
                </tr><?php */?>
                
            </tbody></table>
        </div>
        <?php
		$i++;
		 endforeach; ?>
		 
         
        

views/complaint/vendor.php
<?php 
use yii\helpers\Html;
use yii\widgets\ActiveForm;

 use yii\helpers\BaseHtml;
 use yii\helpers\Url;
 use yii\helpers\ArrayHelper;
 use kartik\grid\GridView;
 use yii\data\ActiveDataProvider;
 use \app\models\Articles;
 //use app\models\Orders;
 use yii\data\SqlDataProvider;


$this->title = 'Suppliers | '.Yii::$app->mycomponent->Get_settings('company_name'); 
/*$merchant_id= Yii::$app->user->identity->merchant_id;
$users=Yii::$app->mycomponent->All_users();
$Orders=Yii::$app->mycomponent->Orders($merchant_id);*/

$bgStatus='';

echo GridView::widget([
    'dataProvider'=>$dataProvider,
    'filterModel'=>$searchModel,
    'showPageSummary'=>true,
    'pjax'=>true,
    'striped'=>true,
    'hover'=>true,
	'headerRowOptions'=>['class'=>'kartik-sheet-style'],
    'filterRowOptions'=>['class'=>'kartik-sheet-style'],
	    'toolbar'=> [
        ['content'=>
            Html::a('<i class="glyphicon glyphicon-plus"></i>', ['newvendor'],['data-pjax'=>0,  'title'=> 'Add', 'class'=>'btn btn-success', ]) . ' '.
            Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['index'], ['data-pjax'=>0, 'class'=>'btn btn-default', 'title'=> 'Reset Grid'])
        ],
        //'{export}',
        '{toggleData}',
    ],
    'panel'=>['type'=>'primary', 'heading'=>'Suppliers'],
    'columns' => [
	       [
		    'label'=>'Company name',
		    'attribute'=>'company_name',
			'value'=>'company_name',
          ],
       
		  [
		    'label'=>'Contact Person',
		    'attribute'=>'first_name',
			'value'=>'first_name',
          ],
		  
		  [
            'attribute'=>'contact_phone',
		  ],
		
		  [
            'attribute'=>'Address',
           
          ],
		  
		 
		  
		  [
		  'label'=>'Email',
            'attribute'=>'email_address',
			'contentOptions' => ['class' => 'text-center'],
			 'headerOptions' => ['class' => 'text-center']
          ],
		
		
		
		
		
		
		
		[
            'attribute'=>'date_created',
            //'pageSummary'=>'Page Summary',
           // 'pageSummaryOptions'=>['class'=>'text-right text-warning'],
        ],
		
		
	
		
		['class' => 'kartik\grid\ActionColumn',
              'header' => 'Actions',
              'template' => '{edit} {delete}',
              'buttons' => [
                
                 'edit' => function ($url, $model) {
                   return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url);
                 },
                 'delete' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url,[
                    'title' => Yii::t('yii', 'Delete'),
                    'data-confirm' => Yii::t('yii', 'Are you sure you want to delete?'),
                    'data-method' => 'post',
                ]);
                 },
              ],
              'urlCreator' => function ($action, $model, $key, $index) {

                if ($action === 'assign') {
                    $url ='' ;
                }
                if ($action === 'edit') {
                    $url = Url::to(['/complaint/updatevendor', 'id' =>$model->id]);
                }
                if ($action === 'delete') {
                    $url = Url::to(['/complaint/deletevendor', 'id' =>$model->id]);
                }                    
                return $url;
            }
          ],
		
    ],
]);


?>
 
 