models/Purchase.php
<?php

namespace app\models;

use Yii;

class Purchase extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
	 // public $shop;
	//  public $vendor_id;
	  
    public static function tableName()
    {
        return 'tbl_purchase';
    }
	 public function getVendor()
	{
		
		 return $this->hasOne(Vendor::className(), ['id' => 'vendor_id']);
		
	}
	 public function getShop1()
	{
		
		 return $this->hasOne(Shop::className(), ['id' => 'shop']);
		
	}
	public function getFirstname() 
	{
       return $this->vendor;
    }
	
	
    public function rules()
    {
        return [
            [['vendor_id','purchase_date', 'shop'], 'required'],
			
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
          
            'purchase_date' => 'Date',
			'shop' => 'Shop',
            
        ];
    }
}

views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<div class="content-wrapper">
   

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">
    copyrights@2017 | MR INFOTECH | Developed by <a href="http://www.fliptech.co.in" target="_blank">Fliptech Solutions</a>
</footer>

views/layouts/header.php
<?php
use yii\helpers\Html;
use lajax\translatemanager\helpers\Language;
/* @var $this \yii\web\View */
/* @var $content string */
?>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-1.10.2.js"></script> 

    <!-- Load jQuery JS -->
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script> 
   
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script> 
    
    <!-- Load SCRIPT.JS which will create datepicker for input field  -->
   

<header class="main-header">

    <?= Html::a('<span class="logo-mini">MR</span><span class="logo-lg">' . Yii::$app->mycomponent->Get_settings('company_name'). '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>
    
    <?php 
	
	 //echo"kk". \lajax\translatemanager\widgets\ToggleTranslate::widget();?>

    <nav class="navbar navbar-static-top" role="navigation">

        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">

                <!-- Messages: style can be found in dropdown.less-->
                
                
                <!-- Tasks: style can be found in dropdown.less -->
                
                <!-- User Account: style can be found in dropdown.less -->

                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <!--  <img src="<?= $directoryAsset;
					 
					   ?>
                      
                       /img/user2-160x160.jpg" class="user-image" alt="User Image"/>-->
                        <span class="hidden-xs"><?php echo ucfirst(Yii::$app->user->identity->firstname); ?><br>
						<?php $roll= Yii::$app->mycomponent->Get_Roll(Yii::$app->user->identity->id); 
						 echo ucfirst($roll);?></span>
                       
                    </a>
                   
                        <!-- Menu Body -->
                       
                        <!-- Menu Footer-->
                       
                              
                </li>

              <li>
      <?= Html::a( '<i class="fa fa-power-off"></i>',['/user-management/auth/logout']) ?>
      </li>
            </ul>
        </div>
    </nav>
</header>

views/layouts/left.php
<?php 
 use yii\widgets\Pjax;

 use webvimark\modules\UserManagement\models\User;
//Pjax::begin(); ?>
<aside class="main-sidebar">

   

        <?php
		if((User::canRoute(['/admin/users'])==1))
		{
			$items[]=['label'=>'Staffs',  'icon' => 'fa fa-user','url'=>['/admin/users'], 'active' => in_array(Yii::$app->controller->action->id,['users','newuser','updateuser'])];
		}
		
		if((User::canRoute(['/complaint/customers'])==1) && (User::canRoute(['/complaint/vendor'])==1))
        {
	         $items[]=['label' => 'Users','url'=>'#','icon' => 'fa fa-user', 'items' => [
				['label'=>'Customers',  'icon' => 'fa fa-user','url'=>['/complaint/customers'], 'active' => in_array(Yii::$app->controller->action->id,['customers','newcustomer','updatecustomer'])],
                ['label'=>'Vendors', 'icon' => 'fa fa-user','url'=>['/complaint/vendor'], 'active' => in_array(Yii::$app->controller->action->id,['vendor','newvendor','updatevendor'])],
				]];
         }
		
        echo dmstr\widgets\Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu'],
                'items' =>
				 [
                    ['label' => 'Menu Yii2', 'options' => ['class' => 'header']],
					['label' => 'Merchant Add','icon' => 'fa fa-cutlery', 'url' => ['admin/register']],
                    ['label' => 'Gii', 'icon' => 'fa fa-file-code-o', 'url' => ['/gii']],
                    ['label' => 'Debug', 'icon' => 'fa fa-dashboard', 'url' => ['/debug']],
                    ['label' => 'Login', 'url' => ['site/login'], 'visible' => Yii::$app->user->isGuest],
                    [
                        'label' => 'Same tools',
                        'icon' => 'fa fa-share',
                        'url' => '#',
                        'items' => [
                            ['label' => 'Gii', 'icon' => 'fa fa-file-code-o', 'url' => ['/gii'],],
                            ['label' => 'Debug', 'icon' => 'fa fa-dashboard', 'url' => ['/debug'],],
                            [
                                'label' => 'Level One',
                                'icon' => 'fa fa-circle-o',
                                'url' => '#',
                                'items' => [
                                    ['label' => 'Level Two', 'icon' => 'fa fa-circle-o', 'url' => '#',],
                                    [
                                        'label' => 'Level Two',
                                        'icon' => 'fa fa-circle-o',
                                        'url' => '#',
                                        'items' => [
                                            ['label' => 'Level Three', 'icon' => 'fa fa-circle-o', 'url' => '#',],
                                            ['label' => 'Level Three', 'icon' => 'fa fa-circle-o', 'url' => '#',],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ]
        ) ?>
    </section>

</aside>
<?php //Pjax::end(); ?>

views/layouts/left1.php
<?php 
 use yii\widgets\Pjax;

//Pjax::begin(); 
       
			$menus=Yii::$app->mycomponent->menu();
		


?>
<aside class="main-sidebar">

<?php
use webvimark\modules\UserManagement\components\GhostMenu;
use webvimark\modules\UserManagement\components\GhostNav;
use webvimark\modules\UserManagement\UserManagementModule;
use webvimark\modules\UserManagement\models\User;
echo GhostMenu::widget([
    'encodeLabels'=>true,
    'activateParents'=>true,
    'items' => [
        [
           // 'label' => 'Backend routes',
            //'items'=>UserManagementModule::menuItems()
        ],
        [
           // 'label' => 'Frontend routes',
            'items'=>[
               
				['label'=>'Users',  'icon' => 'fa fa-user','url'=>['/admin/users'], 'active' => in_array(Yii::$app->controller->action->id,['users','newuser','updateuser'])],
				['label'=>'Job Cards',  'icon' => 'fa fa-user','url'=>['/complaint/'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['complaint/index','complaint/register'])],
				['label'=>'My Jobs',  'icon' => 'fa fa-user','url'=>['/complaint/newcomplaint']],
				['label'=>'Customers',  'icon' => 'fa fa-user','url'=>['/complaint/customers'], 'active' => in_array(Yii::$app->controller->action->id,['customers','newcustomer','updatecustomer'])],
                ['label'=>'Vendors', 'url'=>['/complaint/vendor'], 'active' => in_array(Yii::$app->controller->action->id,['vendor','newvendor','updatevendor'])],
				
				['label' => 'Accessories', 'items' => [
				['label'=>'Category of Accessories', 'url'=>['/inventory/cataccessories'], 'active' => in_array(Yii::$app->controller->action->id,['cataccessories','newcataccesories','updatecateaccessories'])],
				['label'=>'Accessories', 'url'=>['/inventory/accessories'], 'active' => in_array(Yii::$app->controller->action->id,['accessories','newaccesories','updateaccessories'])]
				]],
				['label'=>'Shops', 'url'=>['/inventory/shop'], 'active' => in_array(Yii::$app->controller->action->id,['shop','newshop','updateshop'])],
				['label'=>'Products', 'url'=>['/inventory/products'], 'active' => in_array(Yii::$app->controller->action->id,['products','newproduct','updateproducts'])],
				['label'=>'Purchase', 'url'=>['/inventory/purchase'] , 'active' => in_array(Yii::$app->controller->action->id,['purchase','newpurchase','updatepurchase'])],
				['label'=>'Store', 'url'=>['/store/'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['store/index','store/newsales','store/updatesales'])],
				['label'=>'Sales', 'url'=>['/inventory/sales'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['inventory/sales','inventory/newsales','inventory/updatesales'])],
				['label'=>'Stock',  'icon' => 'fa fa-user','url'=>['/store/stock']],
				['label'=>'Change own password', 'url'=>['/user-management/auth/change-own-password']],
                /*['label'=>'Password recovery', 'url'=>['/user-management/auth/password-recovery']],
                ['label'=>'E-mail confirmation', 'url'=>['/user-management/auth/confirm-email']],*/
            ],
        ],
    ],
]);
//echo Yii::$app->controller->action->id;
?>

   

    </section>

</aside>

<?php 
//print_r(Yii::$app->authManager->getRoles());

/*?><ul class='sidebar-menu'>
<?php 

 foreach($menus as $menu):
 
 $check_url=User::canRoute($menu['url']);
 if($check_url==1)
 {
	 
	   if (strpos($menu['active'], Yii::$app->controller->action->id) !== false) 
		{
			$class='class="active"';
			
		}
		else
		{
			$class='';
			
		}
		$url=array($menu['url']);

	  ?>
 <li <?php echo $class; ?>><a href="<?php echo ($url[0]);?>"><i class="<?php echo $menu['icon'];?>"></i> <span><?php echo $menu['label'];?></span></a></li>
	 
<?php } endforeach; ?>
     </ul>
     </section>
     </aside><?php */?>

views/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */


if (Yii::$app->controller->action->id === 'login') { 
/**
 * Do not use this code in your template. Remove it. 
 * Instead, use the code  $this->layout = '//main-login'; in your controller.
 */
    echo $this->render(
        'main-login',
        ['content' => $content]
    );
} else {

    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\assets\AppAsset::register($this);
    }

    dmstr\web\AdminLteAsset::register($this);

    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
	
    ?>
    
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
    <?php $this->beginBody() ?>
    <div class="wrapper">

        <?= $this->render(
            'header.php',
            ['directoryAsset' => $directoryAsset]
        ) ?>

        <?= $this->render(
            'sidebar.php',
            ['directoryAsset' => $directoryAsset]
        )
        ?>

        <?= $this->render(
            'content.php',
            ['content' => $content, 'directoryAsset' => $directoryAsset]
        ) ?>

    </div>

    <?php $this->endBody() ?>
    </body>
    </html>
    <?php $this->endPage() ?>
<?php } ?>

views/layouts/sidebar.php
<style>

.scroll_fix {
	overflow: scroll;
    overflow-x: hidden;
    height: 550px;
    margin-right: -17px;
    /*padding-right: 84px;*/
	
	
  /*  position: fixed;
    width: 248px;
    overflow-y: scroll;
    top: 0;
    bottom: 0;*/
}
</style>
<?php 
 use kartik\sidenav\SideNav;
 use webvimark\modules\UserManagement\components\GhostNav;
use webvimark\modules\UserManagement\UserManagementModule;
 use webvimark\modules\UserManagement\models\User;
$permission=['/complaint/'];
//echo "kk".$superAdminAllowed;
//echo User::canRoute($permission);
 $type='SideNav::TYPE_PRIMARY';
 $item='1';
use yii\helpers\Url;
echo '<aside class="main-sidebar">';


$items=array();
$Customers='';
$Vendors='';
$Categories='';
$Accessories='';
$Shops='';
$Purchase='';
$Sales='';
$Store='';
$Selling='';
$complaints='';
$products='' ;
$product_type='';
$manufacture='';
$voucher=''; 
$General='';
$General_income='';
$receipt='';
$vat='' ;
$expense='';
$income='';
$general_settings='';
$main_accessories='';
$adminattendance='';
$userattendance='';
$attendance_reports='';
$reportsattanance='';
 $salesReports='';
 $purchaseReports='';
 $receiptReports='';
 $voucherReports='';
 $expenseReports='';
 $incomeReports='';
 $stock='';
  $accounts='';
if((User::canRoute(['/admin/users'])==1))
{
	$items[]=['label'=>'Staffs', 'icon' => 'user','url'=>['/admin/users', 'type'=>SideNav::TYPE_SUCCESS], 'active' => in_array(Yii::$app->controller->action->id,['users','newuser','updateuser']), 'class' => 'treeview'];
}
if((User::canRoute(['/complaint/complaint'])==1))
{
	$complaints=['label'=>'Complaints',  'url'=>['/complaint/complaint'], 'active' => in_array(Yii::$app->controller->action->id,['complaint','spares','register'])];
}
if((User::canRoute(['/complaint/estimate'])==1))
{
	$estimate=['label'=>'Complaint estimates', 'url'=>['/complaint/estimate'], 'active' => in_array(Yii::$app->controller->action->id,['estimate'])];
}

if($complaints!='')
{
	$items[]=['label'=>'Job Cards',  'icon' => 'tag','items' => array_filter([$complaints,$estimate])];
}

if((User::canRoute(['/admin/adminattendance'])==1))
{
	$adminattendance=['label'=>'Attendance', 'url'=>['/admin/adminattendance'], 'active' => in_array(Yii::$app->controller->action->id,['adminattendance'])];
}
if((User::canRoute(['/admin/userattendance'])==1))
{
	$userattendance=['label'=>'User attendance', 'url'=>['/admin/userattendance'], 'active' => in_array(Yii::$app->controller->action->id,['userattendance'])];
}
if((User::canRoute(['/admin/attendance_reports'])==1))
{
	$attendance_reports=['label'=>'Attendance reports', 'url'=>['/admin/attendance_reports'], 'active' => in_array(Yii::$app->controller->action->id,['attendance_reports'])];
}
if((User::canRoute(['/admin/reportsattanance'])==1) && Yii::$app->user->identity->firstname!='superadmin')
{
	$reportsattanance=['label'=>'Attendance reports', 'url'=>['/admin/reportsattanance'], 'active' => in_array(Yii::$app->controller->action->id,['reportsattanance'])];
}

if($adminattendance!='' || $userattendance!='' || $attendance_reports!='' || $reportsattanance!='')
{
	$items[]=['label'=>'Attendance',  'icon' => 'user','items' => array_filter([$adminattendance,$userattendance,$attendance_reports,$reportsattanance])];
}

if((User::canRoute(['/complaint/newcomplaint'])==1) && Yii::$app->user->identity->firstname!='superadmin')
{
	$items[]=['label'=>'My Jobs',  'icon' => 'tag','url'=>['/complaint/newcomplaint']];
}
if((User::canRoute(['/complaint/customers'])==1))
{
	$Customers=['label'=>'Customers',  'icon' => 'user','url'=>['/complaint/customers'], 'active' => in_array(Yii::$app->controller->action->id,['customers','newcustomer','updatecustomer'])];
}
if((User::canRoute(['/complaint/vendor'])==1))
{
	$Vendors=['label'=>'Suppliers', 'icon' => 'user','url'=>['/complaint/vendor'], 'active' => in_array(Yii::$app->controller->action->id,['vendor','newvendor','updatevendor'])];
}
if((User::canRoute(['/inventory/selling'])==1))
{
	$Selling=['label'=>'Discount', 'url'=>['/inventory/selling'], 'active' => in_array(Yii::$app->controller->action->id,['selling','addselling','updateselling'])];
}
if($Customers!='' || $Vendors!='' || $Selling!='')
{
	$items[]=['label' => 'Users','icon' => 'user', 'items' => array_filter([$Customers,$Vendors,$Selling])];
}
if((User::canRoute(['/inventory/cataccessories'])==1))
{
	$Categories=['label'=>'Category of Accessories', 'url'=>['/inventory/cataccessories'], 'active' => in_array(Yii::$app->controller->action->id,['cataccessories','newcataccesories','updatecateaccessories'])];
}
if((User::canRoute(['/inventory/cataccessories'])==1) || (User::canRoute(['/inventory/accessories'])==1))
{
	$Accessories=['label'=>'Accessories', 'url'=>['/inventory/accessories'], 'active' => in_array(Yii::$app->controller->action->id,['accessories','newaccesories','updateaccessories'])];
}

if($Categories!='' || $Accessories!='')
{
	$main_accessories=['label' => 'Accessories','icon' => 'cog', 'items' => array_filter([$Categories,$Accessories])];
}

if((User::canRoute(['/inventory/products'])==1))
{
	$products=['label'=>'Products', 'url'=>['/inventory/products'], 'active' => in_array(Yii::$app->controller->action->id,['products','newproduct','updateproducts'])];
}

if((User::canRoute(['/inventory/product_type'])==1))
{
	$product_type=['label'=>'Product type', 'url'=>['/inventory/product_type'], 'active' => in_array(Yii::$app->controller->action->id,['product_type','addproduct','updateprotype'])];
}

if((User::canRoute(['/inventory/manufacture'])==1))
{
	$manufacture=['label'=>'Manufacture', 'url'=>['/inventory/manufacture'], 'active' => in_array(Yii::$app->controller->action->id,['manufacture','add_manufact','updatemanufact'])];
}


if($products!='' || $product_type!='' || $manufacture!='')
{
	$items[]=['label' => 'Products','icon' => 'wrench', 'items' => array_filter([$product_type,$manufacture,$products])];
}

if((User::canRoute(['/inventory/shop'])==1))
{
	$Shops=['label'=>'Warehouse', 'url'=>['/inventory/shop'], 'active' => in_array(Yii::$app->controller->action->id,['shop','newshop','updateshop'])];
}

if((User::canRoute(['/inventory/opening_stock'])==1))
{
	$stock=['label'=>'Opening Stock', 'url'=>['/inventory/opening_stock'], 'active' => in_array(Yii::$app->controller->action->id,['opening_stock','update_stock','add_stock'])];
}

if((User::canRoute(['/inventory/purchase'])==1))
{
	$Purchase=['label'=>'Purchase' , 'url'=>['/inventory/purchase'] , 'active' => in_array(Yii::$app->controller->action->id,['purchase','newpurchase','updatepurchase'])];
}
if((User::canRoute(['/inventory/sales'])==1))
{
	$Sales=['label'=>'Sales', 'url'=>['/inventory/sales'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['inventory/sales','inventory/newsales','inventory/updatesales'])];
}
if((User::canRoute(['/store/index'])==1))
{
	$Store=['label'=>'Spares', 'url'=>['/store/index'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['store/index','store/newsales','store/updatesales'])];
}


if((User::canRoute(['/inventory/voucher'])==1))
{
	$voucher=['label'=>'Payments', 'url'=>['/inventory/voucher'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['inventory/voucher','inventory/add_voucher','inventory/update_voucher'])];
}
if((User::canRoute(['/inventory/receipt'])==1))
{
	$receipt=['label'=>'Receipt', 'url'=>['/inventory/receipt'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['inventory/receipt','inventory/add_receipt','inventory/update_receipt'])];
}


if($Shops!='' || $Purchase!='' || $Sales!='' || $Store!='' || $stock!='')
{
	$items[]=['label' => 'Inventory','icon' => 'briefcase', 'items' => array_filter([$Shops,$Purchase,$Sales,$stock,$Store])];
}

$General =['label'=>'General Expense','url'=>['/expense/expense'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['expense/expense','expense/add_expense','expense/update_expense'])];
$General_income=['label'=>'General Income','url'=>['/income/income'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['income/income','income/add_income','income/update_income'])];


if($voucher!='')
{
	$items[]=['label' => 'Expense','icon' => 'tasks', 'items' => array_filter([$General,$voucher])];
}

if($receipt!='')
{
	$items[]=['label' => 'Income','icon' => 'tasks', 'items' => array_filter([$General_income,$receipt])];
}

if((User::canRoute(['/store/stock'])==1))
{
	$items[]=['label'=>'Stock',  'icon' => 'tasks','url'=>['/store/stock']];
}

if((User::canRoute(['/settings/settings'])==1))
{
	$general_settings=['label'=>'General Settings','url'=>['/settings/settings'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['settings/settings'])];
}

if((User::canRoute(['/settings/accounts'])==1))
{
	$accounts=['label'=>'Accounts','url'=>['/settings/accounts'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['settings/accounts','settings/add_accounts'])];
}


if((User::canRoute(['/inventory/salesreports'])==1))
{
	$salesReports=['label'=>'Sales Reports', 'url'=>['/inventory/salesreports'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['inventory/salesreports'])];
}
if((User::canRoute(['/inventory/purchasereports'])==1))
{
	$purchaseReports=['label'=>'Purchase Reports', 'url'=>['/inventory/purchasereports'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['inventory/purchasereports'])];
}
if((User::canRoute(['/inventory/receiptreports'])==1))
{
	$receiptReports=['label'=>'Receipt Reports', 'url'=>['/inventory/receiptreports'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['inventory/receiptreports'])];
}
if((User::canRoute(['/inventory/voucherreports'])==1))
{
	$voucherReports=['label'=>'Voucher Reports', 'url'=>['/inventory/voucherreports'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['inventory/voucherreports'])];
}
if((User::canRoute(['/expense/expensereports'])==1))
{
	$expenseReports=['label'=>'Expense Reports', 'url'=>['/expense/expensereports'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['expense/expensereports'])];
}
if((User::canRoute(['/income/incomereports'])==1))
{
	$incomeReports=['label'=>'Income Reports', 'url'=>['/income/incomereports'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['income/incomereports'])];
}



if($salesReports!='' || $purchaseReports!='' || $receiptReports!='' || $voucherReports!='')
{
	$items[]=['label' => 'Reports','icon' => 'th-list', 'items' => array_filter([$salesReports,$purchaseReports,$receiptReports,$voucherReports,$expenseReports,$incomeReports])];
}


if((User::canRoute(['/settings/vat'])==1))
{
	$vat=['label'=>'Vat', 'url'=>['/settings/vat'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['settings/add_vat','settings/vat','settings/update_vat'])];
}
if((User::canRoute(['/settings/expense'])==1))
{
	$expense=['label'=>'Expense Type', 'url'=>['/settings/expense'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['settings/expense','settings/add_expense','settings/update_expense'])];
}
if((User::canRoute(['/settings/income'])==1))
{
	$income=['label'=>'Income Type', 'url'=>['/settings/income'], 'active' => in_array(Yii::$app->controller->id.'/'.Yii::$app->controller->action->id,['settings/income','settings/add_income','settings/update_income'])];
}


if($vat!=''|| $expense!='' || $general_settings!='' || $accounts!='')
{
	$items[]=['label' => 'Settings','icon' => 'wrench', 'items' => array_filter([$general_settings,$accounts,$vat,$expense,$income,$main_accessories])];
}

$items[]=['label'=>'Change own password', 'icon' => 'lock','url'=>['/user-management/auth/change-own-password']];

echo SideNav::widget([
    'type' => $type,
    'encodeLabels' => false,
    'heading' => false,
    'items'=>$items	
]);        
?>
 </section>

</aside>