controllers/StoreController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Purchase;
use app\models\Vendor;
use app\models\Shop;
use app\models\Shopsearch;
use app\models\Purchasesearch;
use app\models\Products;
use app\models\Productsearch;
use app\models\Inventory;
use app\models\Accesories;
use app\models\Stock_reports;
use app\models\Complaint;
use app\models\Complaintsearch;
use app\models\Stocksearch;
use app\models\Sales;
use app\models\Group_sales;
use yii\helpers\ArrayHelper;

class StoreController extends Controller
{
    /**
     * @inheritdoc
     */
	// public $layout=false;
    public function behaviors()
    {
       return [
        'ghost-access'=> [
            'class' => 'webvimark\modules\UserManagement\components\GhostAccessControl',
        ],
    ];
    }

    
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
	  public function actionIndex()
    {
       	$searchModel = new Complaintsearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize=10;
		$dataProvider->setSort([
        'defaultOrder' => ['priority'=>SORT_DESC],]);
        return $this->render('complaint', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
	
	  public function actionStock()
    {
       	$searchModel = new Stocksearch();
		$description='';
		if(isset($_GET['description']))
		{
		 $description=$_GET['description'];
		}
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$description);
        $dataProvider->pagination->pageSize=10;
		/*$dataProvider->setSort([
        'defaultOrder' => ['id'=>SORT_DESC],]);*/
        return $this->render('stock', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
			'description' => $description,
        ]);
    }
	
	 public function actionStockreports()
    {
       	$searchModel = new Stock_reports();
		$product_id='';
		if(isset($_GET['id']))
		{
		 $product_id=$_GET['id'];
		}
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$product_id);
        $dataProvider->pagination->pageSize=10;
		
        return $this->render('stock_reports', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
			//'description' => $description,
        ]);
    }
	 
	 
	 public function actionNewsales()
    {
				$model = new Purchase();
				
				$items1 = ArrayHelper::map(Shop::find()->all(), 'id', 'shop');
				$product_details = ArrayHelper::map(Products::find()->all(), 'pid', 'product_name');
				if ($model->load(Yii::$app->request->post()))
				 {
					$model->shop = $_POST['Purchase']['shop'];
					$product_id=$_POST['product_id'];
					$quantity=$_POST['qty'];
					$price=$_POST['price'];
					  $complaint_id=$_POST['complaint_id'];
					  Inventory::deleteAll(['complaint_id' =>$complaint_id]);
						for($i=0;$i<count($product_id);$i++)
						{
							$Inventory = new Inventory();
							$Inventory->complaint_id =$complaint_id;
							$Inventory->product_id =$product_id[$i];
							$Inventory->sold_price =$price[$i];
							$Inventory->qty ='-'.$quantity[$i];
							$Inventory->shop =$model->shop;
							$Inventory->type ='sales';
							$Inventory->save();
							//$Products->isNewRecord = true;
						}
						  return Yii::$app->response->redirect(array('store/index'));
				
				} 
				else {
					
					  return $this->render('new_purchase', ['model' => $model,'items1'=>$items1,'product_details'=>$product_details]);
					}
          }
		 public function actionUpdatesales()
         {
        
        $complaint_id = $_GET['id'];
	//	$model1 = Inventory::findOne(['complaint_id' =>$complaint_id ]);
	    
		$model = new Purchase();
        $items1 = ArrayHelper::map(Shop::find()->all(), 'id', 'shop');
		$product_details = ArrayHelper::map(Products::find()->all(), 'pid', 'product_name');
		
		
	
		
		 if ($model->load(Yii::$app->request->post())) 
		{
			/*$Is_insert_table = Sales::find(['complaint_id' =>$complaint_id])->one();
			echo $Is_insert_table->createCommand()->getRawSql();
			*/
			/*echo $complaint_id;
			$query = Sales::find()->where(['complaint_id' =>$complaint_id]);
           echo $query->createCommand()->sql;*/
			//print_r($Is_insert_table);
			$Is_insert_table = Sales::findOne(['complaint_id' =>$complaint_id]);
			if(isset($Is_insert_table->complaint_id))
			{
				$Sales = Sales::findOne(['complaint_id' =>$complaint_id]);
			    $Sales->service_sno =$Sales['service_sno'];
			}
			else
			{
				$Sales=new Sales();
				$sales_table = Sales::find('not',['service_sno' =>NULL])->orderBy(['(id)' => SORT_DESC])->one();
				$service_sno=$sales_table['service_sno']+1;
				$Sales->service_sno =$service_sno;
			}
			//exit();
            
		            $model->shop = $_POST['Purchase']['shop'];
					$product_id=$_POST['product_id'];
					$quantity=$_POST['qty'];
					$price=$_POST['price'];
					$complaint_id=$_POST['complaint_id'];
					$action=$_POST['action'];
					$total=$_POST['subtotal'];
			        $sno=$_POST['s_no'];
					$main_total=$_POST['total'];
					$discount=$_POST['discount'];
					$vat=$_POST['vat'];
					$trans=$_POST['trans'];
					$customer_id=$_POST['customer_id'];
				
							Inventory::deleteAll(['complaint_id' =>$complaint_id]);
							//Sales::deleteAll(['complaint_id' =>$complaint_id]);
							Group_sales::deleteAll(['complaint_id' =>$complaint_id]);
							//$Delete_product->delete();
					   $Sales->complaint_id = $complaint_id;
					   $Sales->customer_id = $customer_id;
					   $Sales->discount = $discount;
			           $Sales->vat =$vat;
			           $Sales->trans =$trans;
			           $Sales->sales_date = Date('Y-m-d');
			           $Sales->total =array_sum($main_total);
					   
					   if ($Sales->save(false))
					  {
						     $sales_id=$Sales->id;
							 for($i=0;$i<count($product_id);$i++)
							 {
								    $Group_sales = new Group_sales();
									$Group_sales->sales_id=$sales_id;
									$Group_sales->total=$main_total[$i];
									$Group_sales->qty=1;
									$Group_sales->complaint_id =$complaint_id;
									//$Group_sales->customer_id =$customer_id;
									$Group_sales->save();
									$last_group_id=$Group_sales->group_id;
								 
									$Inventory = new Inventory();
									$Inventory->sales_id =$sales_id;
									$Inventory->complaint_id =$complaint_id;
									$Inventory->customer_id =$customer_id;
									$Inventory->product_id =$product_id[$i];
									$Inventory->price =$price[$i];
									$Inventory->total =$total[$i];
					                $Inventory->sno =$sno[$i];
									$Inventory->qty ='-1';
									$Inventory->shop =$model->shop;
									$Inventory->type ='sales';
									$Inventory->group_id_sales =$last_group_id;
									$Inventory->save();
									//$Products->isNewRecord = true;
								}
								if(isset($action))
								{
									return Yii::$app->response->redirect(array('/complaint/complaint'));
								}
								else
								{
								  return Yii::$app->response->redirect(array('store/index'));
								}
								  
					  }
				
            
        } 
		else {
            
			  return $this->render('new_purchase', ['model' => $model,'items1'=>$items1,'product_details'=>$product_details]);
           }
     }
   
        }

views/store/complaint.php
<?php 
use yii\helpers\Html;
use yii\widgets\ActiveForm;

 use yii\helpers\BaseHtml;
 use yii\helpers\Url;
 use yii\helpers\ArrayHelper;
 use kartik\grid\GridView;
 use yii\data\ActiveDataProvider;
 use \app\models\Articles;
 //use app\models\Orders;
 use yii\data\SqlDataProvider;
  use app\models\Inventory;


$this->title = 'Spares | MR infotech'; 
/*$merchant_id= Yii::$app->user->identity->merchant_id;
$users=Yii::$app->mycomponent->All_users();
$Orders=Yii::$app->mycomponent->Orders($merchant_id);*/

$bgStatus=''; ?>
<?php //\yii\widgets\Pjax::begin(); ?>
<?php
//print_r($model);
echo GridView::widget([
    'dataProvider'=>$dataProvider,
    'filterModel'=>$searchModel,
    'showPageSummary'=>true,
    'pjax'=>true,
    'striped'=>true,
    'hover'=>true,
	'headerRowOptions'=>['class'=>'kartik-sheet-style'],
    'filterRowOptions'=>['class'=>'kartik-sheet-style'],
	    'toolbar'=> [
        ['content'=>
                   Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['index'], ['data-pjax'=>0, 'class'=>'btn btn-default', 'title'=> 'Reset Grid'])
        ],
        '{export}',
        '{toggleData}',
    ],
    'panel'=>['type'=>'primary', 'heading'=>'Spares'],
    'columns' => [
        //'payment_type',
      //  'contact_phone',
       /* 'Title',
        'Published:date',*/
		 /*['class'=>'kartik\grid\SerialColumn',
		 'header' => 'S No',],*/
		 
		 [
			'class'=>'kartik\grid\ExpandRowColumn',
			'width'=>'50px',
			'value'=>function ($model, $key, $index, $column) {
				return GridView::ROW_COLLAPSED;
			},
			'detail'=>function ($model, $key, $index, $column) {
				if ($model->complaint_id!='')
				 {
                   	$model = Inventory::find()->where(['=', 'complaint_id',$model->complaint_id])->all();
                    return Yii::$app->controller->renderPartial('sales', ['model'=>$model]);
				 } 
				 else 
				 {
					return '<div class="alert alert-danger">No data found</div>';
				 }
				
				
				//return Yii::$app->controller->renderPartial('products', ['model'=>$model,'id'=>1]);
			},
			'headerOptions'=>['class'=>'kartik-sheet-style'] 
			//'expandOneOnly'=>true,
		],
		
		
		
		 [
            'attribute'=>'complaint_id',
            //'pageSummary'=>'Complaint id',
           // 'pageSummaryOptions'=>['class'=>'text-right text-warning'],
         ],
		 [
		     'label' => 'Customer name',
            'attribute'=>'first_name',
			'value'=>'customerdetails.first_name',
            //'pageSummary'=>'Page Summary',
           // 'pageSummaryOptions'=>['class'=>'text-right text-warning'],
        ],
		[
            'attribute'=>'customerdetails.Address',
            //'pageSummary'=>'Complaint id',
           // 'pageSummaryOptions'=>['class'=>'text-right text-warning'],
         ],
		  [
            'attribute'=>'customerdetails.contact_phone',
			

            //'pageSummary'=>'Page Summary',
           // 'pageSummaryOptions'=>['class'=>'text-right text-warning'],
        ],
		 
		
		[
    'attribute'=>'status',
	'filter'=>array('pending'=>'pending','Completed'=>'Completed','Rejected'=>'Rejected'),
    'value'=> function($model)
              { 
			   if($model->status == "pending")
              {
                 $status_class = "label-warning";
              }
              else if($model->status == "Completed")
              {
                 $status_class = "label-success";
              }
              else if($model->status == "Rejected")
              {
                 $status_class = "label-danger";
              }
              else
              {
                 $status_class = "label-default";
              }
			  
                   return  Html::a('<span class="label '.$status_class.'">'.$model->status.'</span>', ['complaint/status_change','complaint_id'=>$model->complaint_id], ['class' => 'popupModal']);      
              },
     'format' => 'raw'
],
		
		
		
		
		[

				//'class'=>'kartik\grid\EditableColumn',
				
				'attribute'=>'date_created',
				
				//'pageSummary'=>true,
				
				'filterType' => GridView::FILTER_DATE_RANGE,
				
				'filterWidgetOptions' =>([
				
				//'model'=>$model,
				
				'attribute'=>'date_created',
				
				'presetDropdown'=>TRUE,
				
				'convertFormat'=>true,
				
				'pluginOptions'=> [
				
				'locale'=>['format' => 'Y-m-d H:m:s'],
				
				'opens'=>'left'
				
				]
				
				]),
				
				/*'editableOptions'=> [
				
				'header' => 'term start',
				
				'inputType' => \kartik\editable\Editable::INPUT_TEXT

],
*/



	            'format' => 'raw'		,
			
		
      ],
		
		
	
		
		['class' => 'kartik\grid\ActionColumn',
              'header' => 'Actions',
              'template' => '{edit} {print}',
              'buttons' => [
                 
                 'edit' => function ($url, $model) {
                   return Html::a('<span class="glyphicon glyphicon-plus">Spares</span>',['store/updatesales', 'id' =>$model->complaint_id,'customer_id'=>$model->customer_id]);
                 },
				 'print' => function ($url, $model) {
                   return Html::a('<span class="glyphicon glyphicon-print"></span>', $url,['target'=>'_blank', 'data-pjax'=>"0"]);
                 },
                 
              ],
              'urlCreator' => function ($action, $model, $key, $index) {

                if ($action === 'assign') {
                    $url ='' ;
                }
                if ($action === 'edit') {
                    $url = Url::to(['/complaint/register', 'id' =>$model->complaint_id]);
                }
				if ($action === 'print') {
					$sales = Inventory::find()->where(['=', 'complaint_id',$model->complaint_id])->one();
                    $url = Url::to(['/complaint/bill', 'id' =>$model->complaint_id,'sales_id'=>isset($sales->sales_id)?$sales->sales_id:'','customer_id' =>$model->customer_id]);
                } 
                                 
                return $url;
            }
          ],
		
    ],
]);
?>
<?php
    yii\bootstrap\Modal::begin(['id' =>'modal']);
    yii\bootstrap\Modal::end();
?>
<?php //\yii\widgets\Pjax::end(); ?>
<?php
$Rolls=Yii::$app->mycomponent->GetRolls();

?>
 

<?php
$this->registerJs("$(function() {
   $('.popupModal').click(function(e) {
     e.preventDefault();
     $('#modal').modal('show').find('.modal-content')
     .load($(this).attr('href'));
   });
});"); ?>
 

<div id="state_list"></div>

<div id="receipt"></div>
<input type="hidden" data-toggle="modal" data-target="#show_receipt" class="receipt_trigg"/>

<input type="hidden" data-toggle="modal" data-target="#assign_to" class="assign_to"/>
<input type="hidden" data-toggle="modal" data-target="#stc" class="stc"/>
	<script>
    function assign_complaint(complaint_id) 
    {
    
       // alert(complaint_id);
		$("#cid").val(complaint_id);
		$(".assign_to").trigger('click');
        
    }
    </script>


<script>
function status_change(complaint_id) {
	$.ajax({
	type: "GET",
	url: '<?php echo Yii::$app->request->baseUrl. '/complaint/status_change' ?>',
	data:'complaint_id='+complaint_id,
	success: function(data){
	//alert(data);
		$("#state_list").html(data);
		$("#stc").trigger('click');
	}
	});
}
</script>


<script>
function edit_complaint(order_id) {

//alert(order_id);
	$.ajax({
	type: "GET",
	url: '<?php echo Yii::$app->request->baseUrl. '/complaint/register' ?>',
	data:'order_id='+order_id,
	success: function(data){
	alert(data);
		$("#receipt").html(data);
		$(".receipt_trigg").trigger('click');
	}
	});
}
</script>

<script>
function assign_status(val) {

var status=$('#st').val();
//alert(status);
	$.ajax({
	type: "GET",
	url: '<?php echo Yii::$app->request->baseUrl. '/complaint/status_update' ?>',
	data:'status='+status+'&complaint_id='+val,
	success: function(data){
	//alert("#status_"+val);
	
		$('#modal').modal('hide');
		$.pjax.reload({container:'#w0'});
		
	}
	});
}


</script>


<div class="modal fade" id="assign_to" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div id="tableContainer-1">
    <div id="tableContainer-2">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
		    
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <i class="fa fa-times"></i>
            </button>
          </div>          
          <div id="div-forms" class="dropmenu-div" style="padding:10px;">
            <form class="form form-horizontal" name="" method="post"  >            
                
                 <input type="hidden" id='cid' name="cid"  />
                            
               <div class="form-group row">
               <label class="control-label col-sm-4"  value="Schema Name">Assign to </label>
               <div class="col-sm-8"> 
			   <select name="role" id="role" class="form-control" id="week-list">
               <?php foreach($Rolls as $rolle) { ?>
                  <option value="<?php echo $rolle['item_name'] ?>"><?php echo ucfirst($rolle['item_name']) ?></option>
                  
                  <?php } ?>
               </select>
			   </div> 
               </div>
               
               <div class="form-group row">
               <label class="control-label col-sm-4"  value="Schema Name">Notes</label>
               <div class="col-sm-8"> 
			  <textarea name="notes" id="notes" style="width: 100%;min-height: 100px;"></textarea>
			   </div> 
               </div>
              
            <div class="form-group row">
              <div class="text-center">
               
           <input class="btn btn-success" type="button" onclick="st_assign()" name="smt"  value="Assign" />
           <input class="btn btn-danger" type="submit"  data-dismiss="modal" value="Cancel" aria-label="Close"/>
            
           </div>
           </div>
            </form>        
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
function st_assign()
 {

var cid=$('#cid').val();
var notes=$('#notes').val();
var role=$('#role').val();
//alert(status);
	$.ajax({
	type: "POST",
	url: '<?php echo Yii::$app->request->baseUrl. '/admin/roleassign' ?>',
	data:'cid='+cid+'&notes='+notes+'&role='+role,
	success: function(data){
	//alert(data);
	
		//$("#status_"+val).html(data);
		$(".close").trigger('click');
	}
	});
}


</script>
        



<!-- View receipt button -->



<!--<a class="btn btn-info btn-lg" data-toggle="modal" data-target="#show_receipt">View Receipt</a>-->

views/store/sales.php
<?php
//print_r($model->products);
$products=$model;
//echo 'Hi';
$i=1;
 use app\models\Products;
?>
<?php foreach($products as $val): ?>
<div class="col-sm-4">
            <table class="table table-bordered table-condensed table-hover small kv-table">
                <tbody><tr class="danger">
                    <th colspan="3" class="text-center text-danger">Product <?php echo $i; ?></th>
                </tr>
                <!--<tr class="active">
                    <th class="text-center">#</th>
                    <th>Breakup</th>
                    <th class="text-right">Price</th>
                </tr>-->
                <tr>
                    <td class="text-center">1</td><td><?php echo 'Product_id'; ?></td><td class="text-right"><?php echo $val['product_id']; ?> </td>
                </tr> 
                <tr>
                    <td class="text-center">1</td><td><?php echo 'Product_Name'; ?></td><td class="text-right"><?php  $model1 = Products::findOne(['pid'=>$val['product_id']]); echo $model1->product_name; ?> </td>
                </tr>
                <tr>
                    <td class="text-center">2</td><td><?php echo 'Quantity'; ?></td><td class="text-right"><?php echo abs($val['qty']); ?> </td>
                </tr>
                <tr>
                    <td class="text-center">3</td><td><?php echo 'Price'; ?></td><td class="text-right"><?php echo $val['sold_price']; ?> </td>
                </tr>
                <?php /*?><tr>
                    <td class="text-center">3</td><td><?php echo 'Shop'; ?></td><td class="text-right"><?php echo $val['shop']; ?> </td>
                </tr><?php */?>
                
            </tbody></table>
        </div>
        <?php
		$i++;
		 endforeach; ?>
		 
         
        

views/store/stock_reports.php
<?php 
use yii\helpers\Html;
use yii\widgets\ActiveForm;

 use yii\helpers\BaseHtml;
 use yii\helpers\Url;
 use yii\helpers\ArrayHelper;
 use kartik\grid\GridView;
 use yii\data\ActiveDataProvider;
 use \app\models\Articles;
 //use app\models\Orders;
 use yii\data\SqlDataProvider;
  use app\models\Inventory;


$this->title = 'Stock Reports | '.Yii::$app->mycomponent->Get_settings('company_name');; 
/*$merchant_id= Yii::$app->user->identity->merchant_id;
$users=Yii::$app->mycomponent->All_users();
$Orders=Yii::$app->mycomponent->Orders($merchant_id);*/



$bgStatus=''; ?>
<?php //\yii\widgets\Pjax::begin(); ?>

<?php
//print_r($dataProvider);
echo GridView::widget([
    'dataProvider'=>$dataProvider,
    'filterModel'=>$searchModel,
    'showPageSummary'=>true,
    'pjax'=>true,
    'striped'=>true,
    'hover'=>true,
	//'options'=>[],
	'headerRowOptions'=>['class'=>'kartik-sheet-style'],
    'filterRowOptions'=>['class'=>'kartik-sheet-style'],
	
	    'toolbar'=> [
		'<div style="float:left; margin-right: 600px;" >PRODUCT ID : <b> '.$_GET['id'].'</b>
		</div>',
		
        ['content'=>
		
                   Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['stockreports'], ['data-pjax'=>0, 'class'=>'btn btn-default', 'title'=> 'Reset Grid'])
        ],
        '{export}',
        '{toggleData}',
    ],
    'panel'=>['type'=>'primary', 'heading'=>'Stock Reports'],
    'columns' => [
	
	   
		 [
            'label'=>'Product Name',
			'attribute' => 'product_name',
			'value' => 'product.product_name',
			
           
         ],
		  [
            'label'=>'Product Model',
			'attribute' => 'product_model',
			'value' => 'product.product_model',
			
           
         ],
		 [
            'label'=>'Manufacturer',
			'attribute' => 'manufacturer',
			'value' => 'product.manufacturer',
			
           
         ],
		 
		 [
            'label'=>'S.NO',
			'attribute' => 'sno',
			'value' => 'sno',
			
           
         ],
    
		 [
		    'label' => 'Selling Price',
            'attribute'=>'selling_price',
			//'contentOptions' => ['class' => 'text-center'],
			//'width'=>'10%',
         ],
		
	
		
    ],
]);
?>